### ISSUE TITLE
Crash when load a skin folder

### ISSUE THREAD

**Issue by Moewagon** [insomnyawolf/OsuSkiningTools#1]

**Comment by insomnyawolf** [comment]
Are you using a valid skin folder? 
It must have a "skin.ini" file to work

**Comment by Moewagon** [comment]
Here is a video of the problem

https://streamable.com/ngmunb

**Comment by insomnyawolf** [comment]
Try doing the same with [this version](https://github.com/insomnyawolf/OsuSkiningTools/releases/tag/0.0.0.2), it now has a crash window that will give us some information

**Comment by insomnyawolf** [comment]
There's a more updated version just in case [0.0.0.3](https://github.com/insomnyawolf/OsuSkiningTools/releases/tag/0.0.0.3)

**Comment by Moewagon** [comment]
Okay thats fixed, thanks
